### ISSUE TITLE
Changing the widget-bot name

### ISSUE THREAD

**Issue by OutragedMetro** [widgetbot-io/documentation#6]
Is it possible to change the name of the widget bot on the discord server or is that possible?

**Comment by advaith1** [comment]
You can change its nickname by right click > change nickname like any other users or bot. If you want to actually change the username you will have to host it yourself and on your own bot account.

**Comment by OutragedMetro** [comment]
I am not seeing the documentation for hosting it myself?

**Comment by advaith1** [comment]
There isn't documentation yet, you'll need to download it and build it yourself

**Comment by OutragedMetro** [comment]
Will there be any documentation coming soon?

**Comment by advaith1** [comment]
Probably not unless someone contributes it
